#!/usr/bin/env bash

BBB=${BBB:-192.168.7.2}

function _poweroff {
    # eject if mounted
    if uname -a | grep -q Darwin; then
        dev="$(mount | awk '$3 == "/Volumes/BEAGLEBONE" {print $1}')"
        if [[ -n $dev ]]; then
            diskutil eject "$dev"
        fi
    else
        echo "not implement yet" >&2
        exit 9
    fi

    # should use pubkey to login
    ssh root@$BBB poweroff
}

function _mnt {
    case "$1" in
        "")           echo "error: no device specified" >&2; exit 1 ;;
        sdcard:[0-9]) dev="/dev/mmcblk0p${1##*:}" ;;
        /dev/*)       dev="$1" ;;
        *)            dev="/dev/$1" ;;
    esac

    dst="${2:-/mnt}"

    echo "[+] mounting '$dev' to '$dst'..."
    ssh root@$BBB mount "$dev" "$dst"
}

if [[ $1 == poweroff ]]; then
    _poweroff
elif [[ $1 == mnt ]]; then
    shift
    _mnt "$@"
else
    >&2 echo "usage: ${0##*/} [poweroff|mnt]"
    exit 1
fi
