#!/usr/bin/env bash

cat << EOF
cal -3 with the specified date
usage: $(basename $0) [[[year] month] day]

EOF

case "$#" in
    0) 
       cal -3
       ;;
    1)
        ym="$(date '+%Y-%m')"
        d="$1"
        cal -3 -H "$ym-$d" -d "$ym"
        ;;
    2)
        y="$(date '+%Y')"
        m="$(printf '%02d' $1)"
        d="$2"
        cal -3 -H "$y-$m-$d" -d "$y-$m"
        ;;
    *)
        y="$(printf '%04d' $1)"
        m="$(printf '%02d' $2)"
        d="$3"
        shift 3
        cal -3 -H "$y-$m-$d" -d "$y-$m" "$@"
esac
