#!/usr/bin/env bash

cat << EOF
cal -3 with the specified date
usage: ${0##*/} [[[year] month] day]

EOF


if uname -a | grep -q Darwin; then
    CAL="cal -3"
else
    CAL="ncal -b -3"
fi

case "$#" in
    0) 
       $CAL
       ;;
    1)
        ym="$(date '+%Y-%m')"
        d="$1"
        $CAL -H "$ym-$d" -d "$ym"
        ;;
    2)
        y="$(date '+%Y')"
        m="$(printf '%02s' "$1")"
        d="$2"
        $CAL -H "$y-$m-$d" -d "$y-$m"
        ;;
    *)
        y="$(printf '%04s' "$1")"
        m="$(printf '%02s' "$2")"
        d="$3"
        shift 3
        $CAL -H "$y-$m-$d" -d "$y-$m" "$@"
esac
