#!/bin/bash

if ! uname -a | grep -q Darwin; then
    echo "Only for MAC"
    exit 1
fi    

eject=1

function check_device {
    if [[ ! -e $1 ]]; then
        echo "error: device $1 does not exist"
        exit 2
    fi
}


cmd=$1
disk=$2
img=$3
if [[ -z "$cmd" || -z "$disk" || -z "$img" ]]; then
    cat >&2 <<-EOT
	usage: $(basename "$0") backup diskN NAME.gz"
	       $(basename "$0") restore diskN NAME.gz"
	EOT
    exit 1
fi

dev="/dev/$disk"
rdev="/dev/r$disk"
check_device "$dev"
check_device "$rdev"


if [[ "$cmd" == "backup" ]]; then
    sudo true && sudo dd if="$rdev" bs=1m | pv -s "$sz" | gzip > "$img"
    sz=$(diskutil info "$dev" | grep 'Disk Size' | sed  's/.*(\([0-9][0-9]*\) Bytes).*/\1/')
    [[ -n $eject ]] && diskutil eject "$dev"

elif [ "$cmd" == "restore" ]; then
    diskutil unmountDisk "$dev"
    sz=$(gzip -l "$img" | tail -n1 | awk '{print $2}')
    sudo true && gzip -dc "$img" | pv -s "$sz" | sudo dd of="$rdev" bs=1m
    [[ -n $eject ]] && diskutil eject "$dev"

else
    echo "bad cmd $cmd"
    exit 3
fi
