#!/usr/bin/env python3

import sys
import os

def usage():
    sys.stderr.write("usage: %s <char>" % os.path.basename(sys.argv[0]))

if len(sys.argv) != 2:
    usage()
    exit(1)

char = sys.argv[1]
if len(char) != 1:
    usage()
    exit(1)

count = 0;
for line in sys.stdin:
    for c in line:
        if c == char:
            count += 1

print(count)
