#!/bin/bash

if ! uname -a | grep -q Darwin; then
    echo "Only for MAC"
    exit 1
fi    

bundleid=$1

if [ -z "$bundleid" ]; then
    echo "usage: `basename $0` <bundle-id>"
    exit 1
fi

set -x

#clear
defaults delete $bundleid.LSSharedFileList RecentDocuments

#disable
defaults write $bundleid NSRecentDocumentsLimit 0
defaults write $bundleid.LSSharedFileList RecentDocuments -dict-add MaxAmount 0
