#!/usr/bin/env bash

# https://trac.ffmpeg.org/wiki/Concatenate

listfile=$1
outfile=$2


if [[ -z $listfile || -z $outfile ]]; then
    echo "usage: ${0##*/} <list-file> <output-file>"
    exit 1
fi

ffmpeg -f concat -safe 0 -i "$listfile" -c copy "$outfile"

