#!/bin/bash

if ! uname -a | grep -q Darwin; then
    echo "Only for MAC"
    exit 1
fi    

keyword=$1

if [ -z "$keyword" ]; then
    echo "usage: `basename "$0"` <keyword>"
    exit 1
fi

lsappinfo | grep -i "bundleid.*$keyword" | cut -d= -f2 | sed 's/"\(.*\)"/\1/'

