#!/usr/bin/env bash

function sed {
    if uname -a | grep -q Darwin; then
        command gsed "$@"
    else
        command sed "$@"
    fi
}

read -p "Enter token (empty for removing): " token

# append '@' to a non-empty token if needed
if [[ -n "$token" && "$token" != *@ ]]; then
    token="${token}@"
fi

git remote -v | awk '{print $1, $2}' | sort -u | while read -r source url; do
#                                           |(  scheme  )(  token  )?(path)|
    read -r scheme old_token path < <(sed 's|\([^:]*://\)\([^@]*@\)\?\(.*\)|\1 \2 \3|' <<< "$url")
    if [[ "$old_token" == "${token:0:3}"* ]]; then       # only replace those with the same prefix
        git remote set-url "$source" "${scheme}${token}${path}"
    fi
done

git remote -v
