#!/usr/bin/env bash

function sed {
    if uname -a | grep -q Darwin; then
        command gsed "$@"
    else
        command sed "$@"
    fi
}

read -p "Enter token (empty for removing): " token

# append '@' to a non-empty token if needed
if [[ -n "$token" && "$token" != *@ ]]; then
    token="${token}@"
fi

git remote -v | awk '{print $1, $2}' | sort -u | while read -r source url; do
#                   |(scheme )(  token  )?(path)|
    newurl="$(sed 's|\(.*://\)\([^@]*@\)\?\(.*\)|\1'$token'\3|' <<< "$url")"
    git remote set-url "$source" "$newurl"
done

git remote -v
