#!/usr/bin/env bash

DIR="$(realpath "$0" | xargs dirname)"
DB="$DIR/oui.txt" 

if [[ -z $1 ]]; then
    echo "usage: $(basename $0) <mac-address>"
    echo "usage: echo <mac-address> | $(basename $0) -"
    exit 1
elif [[ $1 == '-' ]]; then
    mac="$(cat)"
else
    mac="$1"
fi

id=$(echo "$mac" | awk -F '[:-]' '{print $1 $2 $3}' OFS='')
vendor="$(grep -i "$id" "$DB" | awk -F '[\t]' '{print $3}')"

echo "$mac: $vendor"
