#!/bin/bash

source "$(dirname "$0")/libs.sh"

cmd="$1"
src="${2%/}"
dst="${3%/}"
if [[ -z "$cmd" || -z "$src" || -z "$dst" ]]; then
    echo "usage: ${0##*/} <cmd> <src-dir> <dst-dir>" >&2
    exit 1
fi

if [[ ! -d "$src" ]]; then
    echo "error: source dir '$src' does not exist" >&2
    exit 2
fi

if [[ -d "$dst" ]]; then
    if ! ask_yesno "Overwrite the dir '$dst' if needed?"; then
        echo "error: user abort" >&2
        exit 3
    fi
fi

mkdir -p "$dst"
find "$src" -type f | sort | while IFS= read -r srcfile;
do
    dstfile="${dst}${srcfile:${#src}}"
    "$cmd" "$srcfile" "$dstfile"
    touch -r "$srcfile" "$dstfile"
done

