#!/usr/bin/env bash

image="$1"
audio="$2"
output="$3"

if [[ -z $image || -z $audio || -z $output ]]; then
    echo "usage: ${0##*/} <image> <audio> <ouput>"
    exit 1
fi

ffmpeg -hide_banner -y -i "$image" -i "$audio" -vcodec mjpeg -framerate 1 -acodec copy "$output"
#ffmpeg -hide_banner -framerate 1 -loop 1 -y -i "$image" -i "$audio" -acodec copy -framerate 1 -vcodec libx264 -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" -shortest "$output"
