#!/usr/bin/env bash

src="$1"
dst="$2"
if [[ -z $src || -z $dst ]]; then
    >&2 echo "usage: $(basename "$0") <src-folder> <dst-iso>"
    exit 1
fi

if uname -a | grep -q Darwin; then
    hdiutil makehybrid -iso -joliet -o "$dst" "$src"
else
    mkisofs -o "$dst" "$src"
fi
