#!/bin/bash

function usage_exit()
{
    >&2 echo "Usage: ${0##*/} <dir> <title> [sn]"
    exit 1
}

dir="${1%/}"
title="$2"
sn="$3"

if [ ! -d "$dir" ]; then
    >&2 echo "No such folder '$dir'."
    usage_exit
fi

if [ -z "$title" ]; then
    >&2 echo "No title specified."
    usage_exit
fi

if [[ -n "$sn" && "$sn" != *. ]]; then
    sn="${sn}."
fi

# clean
chmod o-w "$dir"
find "$dir" \( -name '.DS_Store' -or \
               -name '~uTorrent*.dat' -or \
               -name 'RARBG*' -or \
               -name 'YIYF*.txt' -or \
               -name '*YTS*.jpg' \) -delete
find "$dir" -type f -name '.*' -exec sh -c 'if file "{}" | grep -q AppleDouble; then rm "{}"; fi' \;

# move subtitles
if [[ -d "$dir/Subs" ]];
then
    video="$(find "$dir" -size +100M -type f)"
    count="$(wc -l <<<"$video" | xargs)"
    if [[ "$count" != 1 ]]; then
        >&2 echo "error: cannot identify the video file"
    else
        video="${video##*/}"
        >&2 echo "[+] video file: $video"

        # flaten subtitle files
        basename="${video%.*}"
        for f in "$dir/Subs/"*; do
            [[ -e "$f" ]] || break  # handle the case of no *.wav files
            mv "$f" "$dir/$basename.${f##*/}"
        done
        rmdir "$dir/Subs"

        # rename the country part of filenames
        mv "$dir/$basename".*_Eng*.srt     "$dir/$basename.en.srt" 2>/dev/null
        mv "$dir/$basename".*_Chinese.srt  "$dir/$basename.zh.srt" 2>/dev/null
        mv "$dir/$basename".*_Japanese.srt "$dir/$basename.ja.srt" 2>/dev/null
    fi
fi

# change the folder name
if [[ $(grep -o '\.-' <<< "$dir" | wc -l) -ge 3 ]]; then    # Archive
    sp='\.-'
elif [[ $(grep -o '-' <<< "$dir" | wc -l) -ge 3 ]]; then    # Archive
    sp='-'
elif [[ $dir == *" "* ]]; then                              # YTS
    sp=' '
else                                                        # RARBG
    sp='\.'
fi

# Change Seperator to Comma;
# Camel Case
# Exclude Prepositions
# Insert TITLE and Trim anyting after the year -------
new_dir="$(gsed -E "\
    s#${sp}#.#g; \
    s#(.*)#\L\1#; \
    s#(\.|^)([a-z])#\1\U\2#g; \
    s#\.Of\.#.of.#g; \
    s#\.Or\.#.or.#g; \
    s#\.And\.#.and.#g; \
    s#(.*)\.\(?(19|20)([0-9]{2})\)?(\..*|$)#\1.${title}.\2\3#" <<< "$dir")"
new_dir="${sn}$new_dir"
echo "[+] rename '$dir' => '$new_dir'"
mv "$dir" "$new_dir"

