#!/bin/bash

function usage_exit()
{
    >&2 echo "Usage: ${0##*/} <dir> <title> [sn]"
    exit 1
}

function new_dir()
{
    dirname="$(dirname "$1")"
    name="${1##*/}"
    title="$2"
    sn="$3"

    # change the folder name
    if [[ $(grep -o '\.-' <<< "$name" | wc -l) -ge 3 ]]; then    # Archive
        sp='\.-'
    elif [[ $(grep -o '-' <<< "$name" | wc -l) -ge 3 ]]; then    # Archive
        sp='-'
    elif [[ $name == *" "* ]]; then                              # YTS
        sp=' '
    else                                                        # RARBG
        sp='\.'
    fi

    # Change Seperator to Comma;
    # Camel Case
    # Exclude Prepositions
    # Insert TITLE and Trim anyting after the year -------
    new_name="$(gsed -E "\
        s#${sp}#.#g; \
        s#['\"]##g; \
        s#(.*)#\L\1#; \
        s#(\.|^)([a-z])#\1\U\2#g; \
        s#\.Of\.#.of.#g; \
        s#\.Or\.#.or.#g; \
        s#\.And\.#.and.#g; \
        s#(.*)\.\(?(19|20)([0-9]{2})\)?(\..*|$)#\1.${title}.\2\3#" <<< "$name")"
    new_name="${sn}$new_name"

    echo "$dirname/$new_name"
}

function rm_meta_files {
    dir="$1"

    chmod o-w "$dir"
    find "$dir" \( -name '.DS_Store' -or \
                   -name '~uTorrent*.dat' -or \
                   -name 'RARBG*' -or \
                   -name 'YIYF*.txt' -or \
                   -name 'YTS*.txt' -or \
                   -name '*YTS*.jpg' \
                \) -delete
    find "$dir" -type f -name '.*' -exec sh -c 'if file "{}" | grep -q AppleDouble; then rm "{}"; fi' \;
}

function mv_subtitles {
    dir="$1"

    if [[ ! -d "$dir/Subs" ]]; then
        return 0
    fi

    video="$(find "$dir" -size +100M -type f)"
    count="$(wc -l <<<"$video" | xargs)"
    if [[ "$count" != 1 ]]; then
        >&2 echo "error: cannot identify the video file"
    else
        video="${video##*/}"
        >&2 echo "[+] video file: $video"

        # flaten subtitle files
        basename="${video%.*}"
        for f in "$dir/Subs/"*; do
            [[ -e "$f" ]] || break  # handle the case of no files
            fname="${f##*/}"
            if [[ ${fname} != ${basename}* ]]; then
                fname="$basename.$fname"
            fi
            mv "$f" "$dir/$fname"
        done
        rmdir "$dir/Subs"

        # rename the country part of filenames
        mv "$dir/$basename".*_Eng*.srt     "$dir/$basename.en.srt" 2>/dev/null
        mv "$dir/$basename".*_Chinese.srt  "$dir/$basename.zh.srt" 2>/dev/null
        mv "$dir/$basename".*_Japanese.srt "$dir/$basename.ja.srt" 2>/dev/null
    fi
}

DRYRUN=
if [[ $1 == "-n" || $1 == "--dry-run" ]]; then
    DRYRUN=1
    shift
fi

dir="${1%/}"
title="$2"
sn="$3"

if [[ -z $DRYRUN && ! -d "$dir" ]]; then
    >&2 echo "No such folder '$dir'."
    usage_exit
fi

if [[ -z "$title" ]]; then
    >&2 echo "No title specified."
    usage_exit
fi

if [[ -n "$sn" && "$sn" != *. ]]; then
    sn="${sn}."
fi

dir2="$(new_dir "$dir" "$title" "$sn")"

if [[ -z $DRYRUN ]]; then
    rm_meta_files "$dir"
    mv_subtitles "$dir"
    mv -v "$dir" "$dir2"
else
    echo "mv $dir -> $dir2"
fi
