#!/bin/bash

function usage_exit()
{
    >&2 echo "Usage: ${0##*/} <dir> <title>"
    exit 1
}

dir="${1%/}"
title="$2"

if [ ! -d "$dir" ]; then
    >&2 echo "No such folder '$dir'."
    usage_exit
fi

if [ -z "$title" ]; then
    >&2 echo "No title specified."
    usage_exit
fi

# clean
chmod o-w "$dir"
find "$dir" \( -name '.DS_Store' -or \
               -name '~uTorrent*.dat' -or \
               -name 'RARBG*' -or \
               -name '*YTS*.jpg' \) -delete
find "$dir" -type f -name '.*' -exec sh -c 'if file "{}" | grep -q AppleDouble; then rm "{}"; fi' \;

# move subtitles
if [[ -d "$dir/Subs" ]];
then
    video="$(find "$dir" -size +100M -type f)"
    count="$(wc -l <<<"$video" | xargs)"
    if [[ "$count" != 1 ]]; then
        >&2 echo "error: cannot identify the video file"
    else
        video="${video##*/}"
        >&2 echo "[+] video file: $video"

        # flaten subtitle files
        prefix="${video%.*}"
        for f in "$dir/Subs/"*; do
            [[ -e "$f" ]] || break  # handle the case of no *.wav files
            mv "$f" "$dir/$prefix.${f##*/}"
        done
        rmdir "$dir/Subs"

        # rename the country part of filenames
        mv "$dir/$prefix".*_Eng*.srt    "$dir/$prefix.en.srt" 2>/dev/null
        mv "$dir/$prefix".*_Chinese.srt "$dir/$prefix.zh.srt" 2>/dev/null
    fi
fi

# change the folder name
if [[ $(grep -o '\.-' <<< "$dir" | wc -l) -gt 3 ]]; then      # Archive
    sp='\.-'
elif [[ $dir == *" "* ]]; then                                # YTS
    sp=' '
else                                                          #RARBG
    sp='\.'
fi

#                   Change SP  ; Camel Case              ; Insert TITLE and trme Anyting after the year
new_dir="$(gsed -E 's#'$sp'#.#g; s#(\.|^)([a-z])#\1\U\2#g; s#(.*)\.\(?(19|20)([0-9]{2})\)?\..*#\1.'$title'.\2\3#' <<< "$dir")"
#new_dir="$(gsed -E 's#('$sp'|^)([a-z])#\1\U\2#g; s#(.*)'$sp'\(?(19|20)([0-9]{2})\)?'$sp'.*#\1.'$title'.\2\3#; s#'$sp'#.#g' <<< "$dir")"
echo "[+] rename '$dir' => '$new_dir'"
mv "$dir" "$new_dir"

