#!/usr/bin/env bash

function get_ssid {
    #networksetup -getairportnetwork "$1" | awk '{print $NF}'
    system_profiler -json SPAirPortDataType | \
        jq -r ".SPAirPortDataType[].spairport_airport_interfaces[] | \
            select(._name == \"$1\") | \
            .spairport_current_network_information._name"
}

iface="$1"
ssid="$2"

if [[ -z "$iface" || -z "$ssid" ]]; then
    echo >&2 "usage: ${0##*/} IFACE SSID"
    exit 1
fi

get_ssid "$iface" | grep -q -w "$ssid"

