#!/usr/bin/env bash

function usage {
    >&2 cat <<-EOT
	usage: ${0##*/} <file>
	usage: ${0##*/} --fenc <encoding> <file>
EOT
}

function get_fenc {
    file -I "$1" | sed -n 's/.*charset=\(.*\)/\1/p'
}

# specifed file encoding
if [[ $1 == "--fenc" ]]; then
    fenc="$2"
    shift 2
fi

# set file
file="$1"
if [[ -z "$file" ]]; then
    usage
    exit 1
fi

# detect fileencoding
if [[ -z "$fenc" ]]; then
    fenc="$(get_fenc "$file")"
    if [[ -z "$fenc" ]]; then
        >&2 echo "cannot detect file encoding"
    fi
fi

iconv -f "$fenc" -t utf-8 "$file"

>&2 echo $'\e[0;32m'">> Converted from $fenc to UTF-8 <<"$'\e[0m'
