#!/bin/bash

ebook="$1"
if [[ -z "$ebook" ]]; then
    >&2 echo "usage: ${0##*/} <ebook-file> [dst-pdf]"
    exit 1
fi

if [[ -n "$2" ]]; then
    name="${2%.*}"
else
    name="${ebook%.*}"
fi

extract-volmoe-images "$ebook" "$name"
mkpdf-of-images "$name" "${name}.pdf"

